### ISSUE TITLE
forループの範囲について質問

### ISSUE THREAD

**Issue by naoppy** [key-moon/Library#1]
https://github.com/key-moon/Library/blob/384842f2b256b7e06e1477713450c0a20fb51733/src/Algorithm/String/rolling%20hash.csx#L26

```for (int i = 1; i < powMemo.Length; i++)```は```for (int i = 1; i <= powMemo.Length; i++)```じゃないんですか、間違ってたらすいません

**Comment by key-moon** [comment]
ループの`powMemo[i] = CalcMod(Mul(powMemo[i - 1], Base));`で`powMemo[i - 1]`を基に`powMemo[i]`について計算しているので、境界はこれで合っているはずです

**Comment by naoppy** [comment]
`MAX_LENGTH`と`powMemo.Length`を読み間違えてました
頭たぴでもうしわけない...

**Comment by key-moon** [comment]
なるほど、とにかくissueありがとう
